"""create movie catalog

Revision ID: cefd1f4875a6
Revises:
Create Date: 2026-08-14 17:06:38.400049

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cefd1f4875a6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movies_title"), "movies", ["title"], unique=False)
    op.create_table(
        "movie_genres",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column(
            "genre",
            sa.Enum(
                "action",
                "adventure",
                "animation",
                "comedy",
                "documentary",
                "drama",
                "fantasy",
                "horror",
                "romance",
                "thriller",
                name="genre",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"], ["movies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("movie_id", "genre"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_genres")
    op.drop_index(op.f("ix_movies_title"), table_name="movies")
    op.drop_table("movies")
    # ### end Alembic commands ###
